spring:
  application:
    name: device-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gearcycle}
    username: ${DB_USER:gearcycle}
    password: ${DB_PASSWORD:gearcycle}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
